#
# Dockerized application for tests only
#

FROM webdevops/php-apache-dev:ubuntu-15.10

RUN apt-get -u update && apt-get -y install netcat

COPY ./application /application

WORKDIR /application

#ENTRYPOINT scripts/run_tests.sh

