# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    config.vm.provider "virtualbox" do |v|
      v.memory = 1500
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    config.vm.define "jendoc-app" do |node|

        node.vm.box = "ubuntu/trusty64"

        node.vm.network "forwarded_port", guest: 80, host: 80 #website

        node.vm.hostname = "www.jendocapp.local"

        node.vm.synced_folder "../application", "/var/www/jendocapp"
        node.vm.synced_folder "../docker", "/docker"


        node.vm.provision :shell, path: "bootstrap.sh"

        node.hostmanager.aliases = [
            "phpmyadmin.jendocapp.local",
            "jenkins.jendocapp.local",
            "cadvisor.jendocapp.local",
            "mailcatcher.jendocapp.local",
        ]


    end



end
