# PHPUnit Docker Container.
FROM webdevops/php-apache-dev:ubuntu-15.10

WORKDIR /app

ENTRYPOINT ["vendor/bin/phpunit","--bootstrap","bootstrap.php","tests"]
#ENTRYPOINT ["/usr/local/bin/phpunit"]
#CMD ["--help"]